spring:
  profiles:
    active: dev
---
spring:
  profiles: dev

  application:
    name: affairs-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.43.102:8848

    gateway:
      routes:
        - id: affairs-student
          uri: lb://affairs-student
          predicates:
            - Path=/api/student/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /$\{segment}

        - id: affairs-teacher
          uri: lb://affairs-teacher
          predicates:
            - Path=/api/teacher/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /$\{segment}

        - id: affairs-course
          uri: lb://affairs-course
          predicates:
            - Path=/api/course/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - RewritePath=/api(?<segment>/?.*), /$\{segment}

        - id: affairs-killers
          uri: lb://affairs-killers
          predicates:
            - Path=/api/killers/**
          filters:
            - RewritePath=/api(?<segment>/?.*), /$\{segment}
  redis:
    host: 192.168.56.10

server:
  port: 88
---
spring:
  profiles: pro